// Mirrors backend/app/config/india.py CITY_TO_STATE.
// Keep the two in sync — the backend derives the search region from these names.
export const CITY_TO_STATE = {
  Bengaluru: 'Karnataka',
  Hyderabad: 'Telangana',
  Pune: 'Maharashtra',
  Mumbai: 'Maharashtra',
  'Navi Mumbai': 'Maharashtra',
  Thane: 'Maharashtra',
  Nagpur: 'Maharashtra',
  Nashik: 'Maharashtra',
  Delhi: 'Delhi',
  Gurugram: 'Haryana',
  Noida: 'Uttar Pradesh',
  Ghaziabad: 'Uttar Pradesh',
  Faridabad: 'Haryana',
  Chennai: 'Tamil Nadu',
  Coimbatore: 'Tamil Nadu',
  Madurai: 'Tamil Nadu',
  Kolkata: 'West Bengal',
  Ahmedabad: 'Gujarat',
  Surat: 'Gujarat',
  Vadodara: 'Gujarat',
  Gandhinagar: 'Gujarat',
  Rajkot: 'Gujarat',
  Jaipur: 'Rajasthan',
  Kochi: 'Kerala',
  Thiruvananthapuram: 'Kerala',
  Kozhikode: 'Kerala',
  Chandigarh: 'Chandigarh',
  Mohali: 'Punjab',
  Ludhiana: 'Punjab',
  Indore: 'Madhya Pradesh',
  Bhopal: 'Madhya Pradesh',
  Lucknow: 'Uttar Pradesh',
  Kanpur: 'Uttar Pradesh',
  Visakhapatnam: 'Andhra Pradesh',
  Vijayawada: 'Andhra Pradesh',
  Bhubaneswar: 'Odisha',
  Patna: 'Bihar',
  Ranchi: 'Jharkhand',
  Raipur: 'Chhattisgarh',
  Guwahati: 'Assam',
  Dehradun: 'Uttarakhand',
  Mysuru: 'Karnataka',
  Mangaluru: 'Karnataka',
};

export const INDIAN_CITIES = Object.keys(CITY_TO_STATE).sort();

export const stateForCity = (city) => CITY_TO_STATE[city] || '';
